# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jun Harada
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    原田 惇 / COO / Strategy and Technology Consultant / Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.gijutsuya.jp" # the base hostname & protocol for your site
twitter_username: hrjn
github_username:  harajune

# Build settings
markdown: kramdown
exclude: ["README.md", "s3_website.yml"]
paginate: 5    
gems: ["jekyll-paginate"]
paginate_path: "/blog/page:num"
excerpt_separator: "<!--more-->"
